version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      # POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d/  # Подключаем директорию с SQL-скриптами для инициализации
